set number
set relativenumber

filetype indent plugin on
syntax on

set wildmenu
set hlsearch
nnoremap <C-Y> :nohl<CR><C-Y> " remove highlight with C-Y

" Easier nagivation between splits
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" More natural split locations
set splitbelow
set splitright

set visualbell
set confirm " Asks to save instead of complaining

set shiftwidth=4
set softtabstop=4
set expandtab

set nocompatible             
filetype off                  

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
Plugin 'tpope/vim-sensible'    
Plugin 'junegunn/seoul256.vim'
Plugin 'davidhalter/jedi-vim'
"Plugin 'ambv/black'

call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on

let g:seoul256_background = 233 " 233 (darkest) - 239 (lightest)
colo seoul256
